namespace Capgemini.CodeAnalysis.CoreAnalysers.Test.Constants
{
    public static class CommonConstants
    {
        public static string AutoGeneratedCodeHeaderSingleLineComment => "// <auto-generated> This file has been auto generated. </auto-generated>";

        public static string AutoGeneratedCodeHeader => "//------------------------------------------------------------------------------" +
            "\n// <auto-generated>" +
            "\n//     This code was generated by a tool." +
            "\n//     Runtime Version:4.0.30319.17626" +
            "\n//" +
            "\n//     Changes to this file may cause incorrect behavior and will be lost if" +
            "\n//     the code is regenerated." +
            "\n// </auto-generated>" +
            "\n//------------------------------------------------------------------------------\n";
    }
}