using System.Text;
using Capgemini.CodeAnalysis.CoreAnalysers.Analyzers;
using Capgemini.CodeAnalysis.CoreAnalysers.Test.Constants;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using TestHelper;

namespace Capgemini.CodeAnalysis.CoreAnalysers.Test.Analyzers
{
    [TestClass]
    public class GodClassAnalyzerTests : CodeFixVerifier
    {
        private const int ClassMaxNumberOfPublicMethods = 20;

        [TestMethod]
        public void AnalysisPassesForNoCode()
        {
            var test = string.Empty;

            VerifyCSharpDiagnostic(test);
        }

        [TestMethod]
        public void ClassWithNoPublicMethodPasses()
        {
            var test = @"

    namespace ConsoleApplication1
    {
        public class TypeName
        {              
        }
    }";

            VerifyCSharpDiagnostic(test);
        }

        [TestMethod]
        public void ClassWithSinglePublicMethodAnd19ProtectedMethodsPasses()
        {
            var test = $@"

    namespace ConsoleApplication1
    {{
        public class TypeName
        {{      
            {GeneratePublicMethodText(1)}
            {GenerateProtectedMethodText(19)}
            {GeneratePrivateMethodText(20)}
        }}
    }}";

            VerifyCSharpDiagnostic(test);
        }

        [TestMethod]
        public void ClassWithSinglePublicMethodPasses()
        {
            var test = $@"

    namespace ConsoleApplication1
    {{
        public class TypeName
        {{      
            {GeneratePublicMethodText(1)} 
            {GeneratePrivateMethodText(20)}
        }}
    }}";

            VerifyCSharpDiagnostic(test);
        }

        [TestMethod]
        public void ClassWithSingleProtectedMethodPasses()
        {
            var test = $@"

    namespace ConsoleApplication1
    {{
        public class TypeName
        {{      
            {GenerateProtectedMethodText(1)} 
            {GeneratePrivateMethodText(20)}
        }}
    }}";

            VerifyCSharpDiagnostic(test);
        }

        [TestMethod]
        public void ClassWith20PublicMethodsPasses()
        {
            var test = $@"

    namespace ConsoleApplication1
    {{
        public class TypeName
        {{     
            {GeneratePublicMethodText(20)}
        }}
    }}";

            VerifyCSharpDiagnostic(test);
        }

        [TestMethod]
        public void ClassWith19PublicMethodsPasses()
        {
            var test = $@"

    namespace ConsoleApplication1
    {{
        public class TypeName
        {{     
            {GeneratePublicMethodText(19)}
        }}
    }}";

            VerifyCSharpDiagnostic(test);
        }

        [TestMethod]
        public void ClassWith20PublicMethodsAndOtherOtherPrivateMethodsPasses()
        {
            var test = $@"

    namespace ConsoleApplication1
    {{
        public class TypeName
        {{     
            {GeneratePublicMethodText(20)} 
            {GeneratePrivateMethodText(20)}
        }}
    }}";

            VerifyCSharpDiagnostic(test);
        }

        [TestMethod]
        public void ClassWith20ProtectedMethodsAndOtherOtherPrivateMethodsPasses()
        {
            var test = $@"

    namespace ConsoleApplication1
    {{
        public class TypeName
        {{     
            {GenerateProtectedMethodText(20)} 
            {GeneratePrivateMethodText(20)}
        }}
    }}";

            VerifyCSharpDiagnostic(test);
        }

        [TestMethod]
        public void ClassWith20PublicMethodsAndProtectedMethodsMethodsFails()
        {
            var expected = new DiagnosticResult
            {
                Id = "CAP0008",
                Message = $"{nameof(GodClassAnalyzer)} \'This class has 21 methods which is more than the recommended {ClassMaxNumberOfPublicMethods} methods. \nPlease consider applying the SOLID principles to the class design. \nIt is recommended to have small focused classes.\'",
                Severity = DiagnosticSeverity.Error,
                Locations =
                    new[]
                    {
                        new DiagnosticResultLocation("Test0.cs",  5, 22)
                    }
            };
            var test = $@"

    namespace ConsoleApplication1
    {{
        public class TypeName
        {{     
            {GeneratePublicMethodText(20)}
            {GenerateProtectedMethodText(1)}
            {GeneratePrivateMethodText(20)}
        }}
    }}";

            VerifyCSharpDiagnostic(test, expected);
        }

        [TestMethod]
        public void IgnoresGeneratedSourceCode()
        {
            var test = CommonConstants.AutoGeneratedCodeHeader + $@"

    namespace ConsoleApplication1
    {{
        public class TypeName
        {{     
            {GeneratePublicMethodText(20)}
            {GenerateProtectedMethodText(1)}
            {GeneratePrivateMethodText(20)}
        }}
    }}";

            VerifyCSharpDiagnostic(test);
        }

        [TestMethod]
        public void ClassWithMoreThan20ProtectedMethodsMethodsFails()
        {
            var expected = new DiagnosticResult
            {
                Id = "CAP0008",
                Message = $"{nameof(GodClassAnalyzer)} \'This class has 21 methods which is more than the recommended {ClassMaxNumberOfPublicMethods} methods. \nPlease consider applying the SOLID principles to the class design. \nIt is recommended to have small focused classes.\'",
                Severity = DiagnosticSeverity.Error,
                Locations =
                    new[]
                    {
                        new DiagnosticResultLocation("Test0.cs",  5, 22)
                    }
            };
            var test = $@"

    namespace ConsoleApplication1
    {{
        public class TypeName
        {{      
            {GenerateProtectedMethodText(21)}
            {GeneratePrivateMethodText(20)}
        }}
    }}";

            VerifyCSharpDiagnostic(test, expected);
        }

        [TestMethod]
        public void ClassWith20PublicMethodsAnd1PublicContructorFails()
        {
            var expected = new DiagnosticResult
            {
                Id = "CAP0008",
                Message = $"{nameof(GodClassAnalyzer)} \'This class has 21 methods which is more than the recommended {ClassMaxNumberOfPublicMethods} methods. \nPlease consider applying the SOLID principles to the class design. \nIt is recommended to have small focused classes.\'",
                Severity = DiagnosticSeverity.Error,
                Locations =
                    new[]
                    {
                        new DiagnosticResultLocation("Test0.cs",  5, 22)
                    }
            };
            var test = $@"

    namespace ConsoleApplication1
    {{
        public class TypeName
        {{     
            public TypeName(){{}}
            {GeneratePublicMethodText(20)} 
            {GeneratePrivateMethodText(20)}
        }}
    }}";

            VerifyCSharpDiagnostic(test, expected);
        }

        [TestMethod]
        public void ClassWith20PublicAndProtectedMethodsAnd1PublicContructorFails()
        {
            var expected = new DiagnosticResult
            {
                Id = "CAP0008",
                Message = $"{nameof(GodClassAnalyzer)} \'This class has 21 methods which is more than the recommended {ClassMaxNumberOfPublicMethods} methods. \nPlease consider applying the SOLID principles to the class design. \nIt is recommended to have small focused classes.\'",
                Severity = DiagnosticSeverity.Error,
                Locations =
                    new[]
                    {
                        new DiagnosticResultLocation("Test0.cs", 5, 22)
                    }
            };
            var test = $@"

    namespace ConsoleApplication1
    {{
        public class TypeName
        {{     
            public TypeName(){{}}
            {GeneratePublicMethodText(15)}
            {GenerateProtectedMethodText(5)}
            {GeneratePrivateMethodText(20)}
        }}
    }}";

            VerifyCSharpDiagnostic(test, expected);
        }

        [TestMethod]
        public void ClassWith20PublicAndProtectedMethodsWith1PrivateContructorPasses()
        {
            var test = $@"

    namespace ConsoleApplication1
    {{
        public class TypeName
        {{   
            private TypeName(){{}}
            {GeneratePublicMethodText(3)}
            {GenerateProtectedMethodText(17)}
            {GeneratePrivateMethodText(20)}
        }}
    }}";

            VerifyCSharpDiagnostic(test);
        }

        [TestMethod]
        public void ClassWithMoredThan20PublicAndProtectedMethodsFails()
        {
            var expected = new DiagnosticResult
            {
                Id = "CAP0008",
                Message = $"{nameof(GodClassAnalyzer)} \'This class has 24 methods which is more than the recommended {ClassMaxNumberOfPublicMethods} methods. \nPlease consider applying the SOLID principles to the class design. \nIt is recommended to have small focused classes.\'",
                Severity = DiagnosticSeverity.Error,
                Locations =
                    new[]
                    {
                        new DiagnosticResultLocation("Test0.cs", 5, 22)
                    }
            };

            var test = $@"

    namespace ConsoleApplication1
    {{
        public class TypeName
        {{   
            private TypeName(){{}}
            {GeneratePublicMethodText(13)}
            {GenerateProtectedMethodText(11)}
            {GeneratePrivateMethodText(20)}
        }}
    }}";

            VerifyCSharpDiagnostic(test, expected);
        }

        [TestMethod]
        public void ClassWithMoreThan20PublicMethodsFails()
        {
            var expected = new DiagnosticResult
            {
                Id = "CAP0008",
                Message = $"{nameof(GodClassAnalyzer)} \'This class has 21 methods which is more than the recommended {ClassMaxNumberOfPublicMethods} methods. \nPlease consider applying the SOLID principles to the class design. \nIt is recommended to have small focused classes.\'",
                Severity = DiagnosticSeverity.Error,
                Locations =
                    new[]
                    {
                        new DiagnosticResultLocation("Test0.cs",  5, 22)
                    }
            };
            var test = $@"

    namespace ConsoleApplication1
    {{
        public class TypeName
        {{   
            {GeneratePublicMethodText(21)}
        }}
    }}";

            VerifyCSharpDiagnostic(test, expected);
        }

        protected override DiagnosticAnalyzer GetCSharpDiagnosticAnalyzer()
        {
            return new GodClassAnalyzer();
        }

        private string GeneratePublicMethodText(int numberOfLines)
        {
            var stringBuilder = new StringBuilder();
            for (var counter = 0; counter < numberOfLines; counter++)
            {
                if (counter == numberOfLines - 1)
                {
                    stringBuilder.Append($" public void Method{counter}(){{}}");
                }
                else
                {
                    stringBuilder.AppendLine($" public  void Method{counter}(){{}}");
                }
            }

            return stringBuilder.ToString();
        }

        private string GeneratePrivateMethodText(int numberOfLines)
        {
            var stringBuilder = new StringBuilder();
            for (var counter = 0; counter < numberOfLines; counter++)
            {
                if (counter == numberOfLines - 1)
                {
                    stringBuilder.Append($" private void Method{counter}(){{}}");
                }
                else
                {
                    stringBuilder.AppendLine($" private  void Method{counter}(){{}}");
                }
            }

            return stringBuilder.ToString();
        }

        private string GenerateProtectedMethodText(int numberOfLines)
        {
            var stringBuilder = new StringBuilder();
            for (var counter = 0; counter < numberOfLines; counter++)
            {
                if (counter == numberOfLines - 1)
                {
                    stringBuilder.Append($" protected void Method{counter}(){{}}");
                }
                else
                {
                    stringBuilder.AppendLine($" protected  void Method{counter}(){{}}");
                }
            }

            return stringBuilder.ToString();
        }
    }
}