using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Diagnostics;

namespace Capgemini.CodeAnalysis.CoreAnalysers.Extensions
{
    /// <summary>
    /// Implements bespoke operations to detect auto generated source code or artifacts.
    /// </summary>
    public static class ExcludeGeneratedCodeExtensions
    {
        /// <summary>
        /// Determine if the source code or artifact has been automatically generated.
        /// </summary>
        /// <param name="context">An instance of <see cref="SyntaxNodeAnalysisContext"/> to support the analysis.</param>
        /// <returns><c>true</c> if the code was auto-generated, otherwise <c>false</c>.</returns>
        public static bool IsAutomaticallyGeneratedCode(this SyntaxNodeAnalysisContext context)
        {
            var collection = context.Node.Ancestors();
            foreach (var item in collection)
            {
                if (item.IsGenerated())
                {
                    return true;
                }
                else if (item.SourceCodeIsAutoGenerated())
                {
                    return true;
                }
            }

            return false;
        }

        private static bool IsGenerated(this SyntaxNode node)
        {
            var declaration = node as NamespaceDeclarationSyntax;
            if (declaration == null)
            {
                return false;
            }

            var filePath = declaration.SyntaxTree.FilePath;

            return filePath.IsGeneratedFileName();
        }

        private static bool SourceCodeIsAutoGenerated(this SyntaxNode node)
        {
            var sourceCode = node.SyntaxTree.GetText().ToString();
            return sourceCode.IsSourceCodeAutoGenerated();
        }
    }
}